### PR TITLE
Fixes code blocks showing "undefined"

### LINKED ISSUE #81: Code highlighting issue ("undefined")
While I was using a codellama I came across code blocks which didn't render properly. They showed only as "undefined".
(example prompt: "Can you show me a Swift code snippet?")

The same prompt sent to llama3.1 showed up correctly. So I suppose the problem is due to difference in the output of codellama.

When running the prompt in terminal the difference is obvious: The code block has no language annotation.

    % ollama run codellama:7b
    >>> Can you show me a Swift code snippet?
    Sure! Here is an example of a simple Swift code snippet:
    ```
    let name = "Alice"
    print("Hello, \(name)!")
    ```
    This code defines a variable `name` and sets it to the string "Alice". It then uses string interpolation to print a message to the console that includes 
    the value of the `name` variable.

According to my debugging the language used for the code highlighter is "" (=empty string). It should probably be `nil`.

A simple fix to solve this is adjusting the `highlightCode()` function in CodeHighlighter.swift, checking whether the `language` parameter is empty.

        guard language?.isEmpty == false, 
              let highlightedCode = highlightr.highlight(code, as: language)
        else {
            return Text(code)
        }

### PR DESCRIPTION
**Pull request by pd95**
Fixes #81 by checking `language` for empty string

### CODE REVIEW

File: Ollamac/Views/Subviews/CodeHighlighter.swift [hunk 1]
```diff
@@ -22,10 +22,12 @@ struct CodeHighlighter: CodeSyntaxHighlighter {
     }
     
     func highlightCode(_ code: String, language: String?) -> Text {
-        guard let highlightedCode = highlightr.highlight(code, as: language) else {
+        guard language?.isEmpty == false,
```
Comment (kevinhermawan) [inline Ollamac/Views/Subviews/CodeHighlighter.swift:25]: Nice catch! One suggestion: it would be useful to automatically set the highlight code if the language isn't specified. Here's an example implementation:

```swift
func highlightCode(_ code: String, language: String?) -> Text {
    let highlightedCode: NSAttributedString?

    if let language, !language.isEmpty {
        highlightedCode = highlightr.highlight(code, as: language)
    } else {
        highlightedCode = highlightr.highlight(code)
    }

    guard let highlightedCode else { return Text(code) }

    var attributedCode = AttributedString(highlightedCode)
    attributedCode.font = .system(size: 16, design: .monospaced)

    return Text(attributedCode)
}
```

**Review by kevinhermawan — CHANGES_REQUESTED** [review]

File: Ollamac/Views/Subviews/CodeHighlighter.swift (hunk 1 above)
Comment (pd95) [reply Ollamac/Views/Subviews/CodeHighlighter.swift]: Yes, you are right. Language detection should take over when the language is not set.
Thanks... I fixed it with your version.
